### ISSUE TITLE
Feature Request: Compatibility with Symphony ^3.0

### ISSUE THREAD

**Issue by filipbasara** [terminal42/contao-combinerbundle#1]
Release dev-develop can't be installed under Symphony 3

Error log from Contao Manager

```
/www/composer.json has been updated
Loading composer repositories with package information
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for terminal42/contao-combinerbundle dev-develop -> satisfiable by terminal42/contao-combinerbundle[dev-develop].
    - Conclusion: remove symfony/symfony v3.3.6
    - Conclusion: don't install symfony/symfony v3.3.6
    - terminal42/contao-combinerbundle dev-develop requires symfony/http-kernel ^2.7 -> satisfiable by symfony/http-kernel[v2.7.0, v2.7.1, v2.7.10, v2.7.11, v2.7.12, v2.7.13, v2.7.14, v2.7.15, v2.7.16, v2.7.17, v2.7.18, v2.7.19, v2.7.2, v2.7.20, v2.7.21, v2.7.22, v2.7.23, v2.7.24, v2.7.25, v2.7.26, v2.7.27, v2.7.28, v2.7.29, v2.7.3, v2.7.30, v2.7.31, v2.7.32, v2.7.33, v2.7.4, v2.7.5, v2.7.6, v2.7.7, v2.7.8, v2.7.9, v2.8.0, v2.8.1, v2.8.10, v2.8.11, v2.8.12, v2.8.13, v2.8.14, v2.8.15, v2.8.16, v2.8.17, v2.8.18, v2.8.19, v2.8.2, v2.8.20, v2.8.21, v2.8.22, v2.8.23, v2.8.24, v2.8.25, v2.8.26, v2.8.3, v2.8.4, v2.8.5, v2.8.6, v2.8.7, v2.8.8, v2.8.9].
    - don't install symfony/http-kernel v2.7.0|don't install symfony/symfony v3.3.6
    - don't install symfony/http-kernel v2.7.1|don't install symfony/symfony v3.3.6
    - don't install symfony/http-kernel v2.7.10|don't install symfony/symfony v3.3.6
    - don't install symfony/http-kernel v2.7.11|don't install symfony/symfony v3.3.6
    - don't install symfony/http-kernel v2.7.12|don't install symfony/symfony v3.3.6
    - don't install symfony/http-kernel v2.7.13|don't install symfony/symfony v3.3.6
    - don't install symfony/http-kernel v2.7.14|don't install symfony/symfony v3.3.6
    - don't install symfony/http-kernel v2.7.15|don't install symfony/symfony v3.3.6
    - don't install symfony/http-kernel v2.7.16|don't install symfony/symfony v3.3.6
    - don't install symfony/http-kernel v2.7.17|don't install symfony/symfony v3.3.6
    - don't install symfony/http-kernel v2.7.18|don't install symfony/symfony v3.3.6
    - don't install symfony/http-kernel v2.7.19|don't install symfony/symfony v3.3.6
    - don't install symfony/http-kernel v2.7.2|don't install symfony/symfony v3.3.6
    - don't install symfony/http-kernel v2.7.20|don't install symfony/symfony v3.3.6
    - don't install symfony/http-kernel v2.7.21|don't install symfony/symfony v3.3.6
    - don't install symfony/http-kernel v2.7.22|don't install symfony/symfony v3.3.6
    - don't install symfony/http-kernel v2.7.23|don't install symfony/symfony v3.3.6
    - don't install symfony/http-kernel v2.7.24|don't install symfony/symfony v3.3.6
    - don't install symfony/http-kernel v2.7.25|don't install symfony/symfony v3.3.6
    - don't install symfony/http-kernel v2.7.26|don't install symfony/symfony v3.3.6
    - don't install symfony/http-kernel v2.7.27|don't install symfony/symfony v3.3.6
    - don't install symfony/http-kernel v2.7.28|don't install symfony/symfony v3.3.6
    - don't install symfony/http-kernel v2.7.29|don't install symfony/symfony v3.3.6
    - don't install symfony/http-kernel v2.7.3|don't install symfony/symfony v3.3.6
    - don't install symfony/http-kernel v2.7.30|don't install symfony/symfony v3.3.6
    - don't install symfony/http-kernel v2.7.31|don't install symfony/symfony v3.3.6
    - don't install symfony/http-kernel v2.7.32|don't install symfony/symfony v3.3.6
    - don't install symfony/http-kernel v2.7.33|don't install symfony/symfony v3.3.6
    - don't install symfony/http-kernel v2.7.4|don't install symfony/symfony v3.3.6
    - don't install symfony/http-kernel v2.7.5|don't install symfony/symfony v3.3.6
    - don't install symfony/http-kernel v2.7.6|don't install symfony/symfony v3.3.6
    - don't install symfony/http-kernel v2.7.7|don't install symfony/symfony v3.3.6
    - don't install symfony/http-kernel v2.7.8|don't install symfony/symfony v3.3.6
    - don't install symfony/http-kernel v2.7.9|don't install symfony/symfony v3.3.6
    - don't install symfony/http-kernel v2.8.0|don't install symfony/symfony v3.3.6
    - don't install symfony/http-kernel v2.8.1|don't install symfony/symfony v3.3.6
    - don't install symfony/http-kernel v2.8.10|don't install symfony/symfony v3.3.6
    - don't install symfony/http-kernel v2.8.11|don't install symfony/symfony v3.3.6
    - don't install symfony/http-kernel v2.8.12|don't install symfony/symfony v3.3.6
    - don't install symfony/http-kernel v2.8.13|don't install symfony/symfony v3.3.6
    - don't install symfony/http-kernel v2.8.14|don't install symfony/symfony v3.3.6
    - don't install symfony/http-kernel v2.8.15|don't install symfony/symfony v3.3.6
    - don't install symfony/http-kernel v2.8.16|don't install symfony/symfony v3.3.6
    - don't install symfony/http-kernel v2.8.17|don't install symfony/symfony v3.3.6
    - don't install symfony/http-kernel v2.8.18|don't install symfony/symfony v3.3.6
    - don't install symfony/http-kernel v2.8.19|don't install symfony/symfony v3.3.6
    - don't install symfony/http-kernel v2.8.2|don't install symfony/symfony v3.3.6
    - don't install symfony/http-kernel v2.8.20|don't install symfony/symfony v3.3.6
    - don't install symfony/http-kernel v2.8.21|don't install symfony/symfony v3.3.6
    - don't install symfony/http-kernel v2.8.22|don't install symfony/symfony v3.3.6
    - don't install symfony/http-kernel v2.8.23|don't install symfony/symfony v3.3.6
    - don't install symfony/http-kernel v2.8.24|don't install symfony/symfony v3.3.6
    - don't install symfony/http-kernel v2.8.25|don't install symfony/symfony v3.3.6
    - don't install symfony/http-kernel v2.8.26|don't install symfony/symfony v3.3.6
    - don't install symfony/http-kernel v2.8.3|don't install symfony/symfony v3.3.6
    - don't install symfony/http-kernel v2.8.4|don't install symfony/symfony v3.3.6
    - don't install symfony/http-kernel v2.8.5|don't install symfony/symfony v3.3.6
    - don't install symfony/http-kernel v2.8.6|don't install symfony/symfony v3.3.6
    - don't install symfony/http-kernel v2.8.7|don't install symfony/symfony v3.3.6
    - don't install symfony/http-kernel v2.8.8|don't install symfony/symfony v3.3.6
    - don't install symfony/http-kernel v2.8.9|don't install symfony/symfony v3.3.6
    - Installation request for symfony/symfony (locked at v3.3.6) -> satisfiable by symfony/symfony[v3.3.6].


Installation failed, reverting /www/composer.json to its original content.
--------------------------------------------------------
Exception occured: Error: command exit code was 2
#0 phar:///www/web/contao-manager.phar.php/vendor/tenside/core/src/Task/Composer/AbstractComposerCommandTask.php(166): Tenside\Core\Task\Composer\AbstractComposerCommandTask->executeCommand(Object(Tenside\Core\Task\Composer\WrappedCommand\RequireCommand), Object(Symfony\Component\Console\Input\ArrayInput), Object(Tenside\Core\Task\TaskOutput))
#1 phar:///www/web/contao-manager.phar.php/vendor/tenside/core/src/Task/Task.php(173): Tenside\Core\Task\Composer\AbstractComposerCommandTask->doPerform()
#2 phar:///www/web/contao-manager.phar.php/vendor/tenside/core/src/Task/Runner.php(89): Tenside\Core\Task\Task->perform('/var/www/client...')
#3 phar:///www/web/contao-manager.phar.php/vendor/tenside/core-bundle/src/Command/RunTaskCommand.php(82): Tenside\Core\Task\Runner->run('/var/www/client...')
#4 phar:///www/web/contao-manager.phar.php/vendor/symfony/console/Command/Command.php(264): Tenside\CoreBundle\Command\RunTaskCommand->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#5 phar:///www/web/contao-manager.phar.php/vendor/tenside/core-bundle/src/Command/RunTaskCommand.php(61): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#6 phar:///www/web/contao-manager.phar.php/vendor/symfony/console/Application.php(887): Tenside\CoreBundle\Command\RunTaskCommand->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#7 phar:///www/web/contao-manager.phar.php/vendor/symfony/console/Application.php(223): Symfony\Component\Console\Application->doRunCommand(Object(Tenside\CoreBundle\Command\RunTaskCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#8 phar:///www/web/contao-manager.phar.php/api/ApiApplication.php(71): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#9 phar:///www/web/contao-manager.phar.php/vendor/symfony/console/Application.php(130): Contao\ManagerApi\ApiApplication->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#10 phar:///www/web/contao-manager.phar.php/api/console(74): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#11 /www/web/contao-manager.phar.php(55): require('phar:///var/www...')
#12 {main}
Chained exception: Error: command exit code was 2
#0 phar:///www/web/contao-manager.phar.php/vendor/tenside/core/src/Task/Composer/AbstractComposerCommandTask.php(166): Tenside\Core\Task\Composer\AbstractComposerCommandTask->executeCommand(Object(Tenside\Core\Task\Composer\WrappedCommand\RequireCommand), Object(Symfony\Component\Console\Input\ArrayInput), Object(Tenside\Core\Task\TaskOutput))
#1 phar:///www/web/contao-manager.phar.php/vendor/tenside/core/src/Task/Task.php(173): Tenside\Core\Task\Composer\AbstractComposerCommandTask->doPerform()
#2 phar:///www/web/contao-manager.phar.php/vendor/tenside/core/src/Task/Runner.php(89): Tenside\Core\Task\Task->perform('/var/www/client...')
#3 phar:///www/web/contao-manager.phar.php/vendor/tenside/core-bundle/src/Command/RunTaskCommand.php(82): Tenside\Core\Task\Runner->run('/var/www/client...')
#4 phar:///www/web/contao-manager.phar.php/vendor/symfony/console/Command/Command.php(264): Tenside\CoreBundle\Command\RunTaskCommand->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#5 phar:///www/web/contao-manager.phar.php/vendor/tenside/core-bundle/src/Command/RunTaskCommand.php(61): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#6 phar:///www/web/contao-manager.phar.php/vendor/symfony/console/Application.php(887): Tenside\CoreBundle\Command\RunTaskCommand->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#7 phar:///www/web/contao-manager.phar.php/vendor/symfony/console/Application.php(223): Symfony\Component\Console\Application->doRunCommand(Object(Tenside\CoreBundle\Command\RunTaskCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#8 phar:///www/web/contao-manager.phar.php/api/ApiApplication.php(71): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#9 phar:///www/web/contao-manager.phar.php/vendor/symfony/console/Application.php(130): Contao\ManagerApi\ApiApplication->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#10 phar:///www/web/contao-manager.phar.php/api/console(74): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#11 /www/web/contao-manager.phar.php(55): require('phar:///var/www...')
#12 {main}
--------------------------------------------------------


Process terminated with exit code 1
Reason: General error
```

**Comment by aschempp** [comment]
what are you trying to do with this bundle?

**Comment by filipbasara** [comment]
@aschempp I'm trying to combine js files.
Issue appears during installation.
